# Generated by Django 5.0.3 on 2024-03-23 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('category_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=255)),
                ('location_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=255)),
                ('user_role', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('asset_tag', models.CharField(max_length=255)),
                ('equipment_name', models.CharField(max_length=255)),
                ('equipment_description', models.TextField()),
                ('equipment_type', models.CharField(max_length=255)),
                ('equipment_availability', models.BooleanField(default=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('equipment_status', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='GroupAcw.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='GroupAcw.location')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reservation_status', models.CharField(max_length=255)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GroupAcw.equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GroupAcw.user')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_date', models.DateTimeField()),
                ('alert_type', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GroupAcw.reservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GroupAcw.user')),
            ],
        ),
    ]
